name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        id: gradle-build
        run: ./gradlew build --no-daemon

  release:
      needs: build
      if: ${{ success() }}
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v3
          with :
            ref : ${{ github.ref }}
            tag_name : ${{ steps.create_release.outputs.tag_name }}
        - name: Release
          uses: softprops/action-gh-release@v1
