name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        id: gradle-build
        run: ./gradlew build --no-daemon

  release:
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref.split('/')[2] }} # Extract the tag name without the 'refs/' prefix
          release_name: Release ${{ github.ref.split('/')[2] }} # Use the same tag name as the release name
          body: |
            Release ${{ github.ref.split('/')[2] }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: build/libs/*.jar
