name: Java CI with Gradle

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Extract Version from build.gradle.kts
        id: extract-version
        run: echo "version=\$(grep '^version = ' build.gradle.kts | sed 's/version = \"\\(.*\\)\"/\\1/')" >> $GITHUB_ENV

      - name: Output Application Version
        run: echo "version $version"

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  create-tag:
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract Version from build.gradle.kts
        id: extract-version
        run: echo "version=\$(grep '^version = ' build.gradle.kts | sed 's/version = \"\\(.*\\)\"/\\1/')" >> $GITHUB_ENV
      - name: Create Tag
        run: git tag ${{ env.version }}
      - name: Push Tag to Remote Repository
        run: git push origin ${{ env.version }}
