name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        id: gradle-build
        run: ./gradlew build --no-daemon

      - name: Extract Version from build.gradle.kts
        id: extract-version
        run: echo "version=\$(grep '^version = ' build.gradle.kts | sed 's/version = \"\\(.*\\)\"/\\1/')" >> $GITHUB_ENV

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*
          tag_name: ${{ github.ref }}
          body: ${{ github.event.release.body }}
          draft: false
          prerelease: false
